/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.40.0.12
 *
 * Project: 'Basisproject' 
 * Target:  'Target_1' 
 */

#ifndef PRE_INCLUDE_GLOBAL_H
#define PRE_INCLUDE_GLOBAL_H

/* Keil::Device&Standalone:Startup@1.0.0 */
#define USE_HAL_DRIVER
          #define USE_FULL_LL_DRIVER


#endif /* PRE_INCLUDE_GLOBAL_H */
